#cloud-config
users:
  - name: ${admin_user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}
    lock_passwd: false
    passwd: "${admin_password}"
packages:
  - net-tools
runcmd:
  # Change SSH port to tcp:2222 (compliance requirement)
  - sed -i "s/#Port 22/Port 2222/" /etc/ssh/sshd_config
  - systemctl restart sshd
